USE sucos_vendas;

SELECT * FROM tabela_de_produtos;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
	CASE
		WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
        WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
        ELSE 'PRODUTO BARATO'
	END AS STATUS_PRECO 
FROM tabela_de_produtos
ORDER BY PRECO_DE_LISTA;

SELECT EMBALAGEM,
	CASE
		WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
        WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
        ELSE 'PRODUTO BARATO'
	END AS STATUS_PRECO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM tabela_de_produtos
GROUP BY EMBALAGEM,
	CASE
		WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
        WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
        ELSE 'PRODUTO BARATO'
	END 
ORDER BY EMBALAGEM;
    
    
SELECT * FROM tabela_de_clientes
	WHERE DATA_DE_NASCIMENTO < '1989-01-01';

SELECT NOME, DATA_DE_NASCIMENTO,
	CASE
		WHEN DATA_DE_NASCIMENTO < '1990-01-01' THEN 'VELHOS'
        WHEN DATA_DE_NASCIMENTO >= '1990-01-01' AND DATA_DE_NASCIMENTO < '1996-01-01' THEN 'JOVENS'
        WHEN DATA_DE_NASCIMENTO >= '1996-01-01' THEN 'CRIANÇAS'
       
	END AS FAIXA_ETARIA 
    FROM tabela_de_clientes
    ORDER BY DATA_DE_NASCIMENTO;
    
SELECT NOME,
	CASE
		WHEN YEAR(DATA_DE_NASCIMENTO) < 1990 THEN 'VELHO'
        WHEN YEAR(DATA_DE_NASCIMENTO) >= 1990 AND YEAR(DATA_DE_NASCIMENTO) <= 1995 THEN 'JOVENS'
        ELSE 'CRIANÇAS'
	END AS 'CLASSIFICAÇÃO POR IDADE'
    FROM tabela_de_clientes;
    


    